#language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shashankbenegal/docker-react -f Dockerfile.dev .

script:
#  - docker run shashankbenegal/docker-react npm run test -- --coverage
  - docker run -e CI=true shashankbenegal/docker-react npm run test 